language: python
python:
  - "3.7"
  - "3.8"
# command to install dependencies
install:
  - pip install -r requirements.txt
addons:
  mariadb: '10.4'
services:
  - mysql
before_script:
  - sudo 
# command to run tests
script: 
  - python example.py
